### ISSUE TITLE
Random wishlist

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/mdef-docs#5]
- [x] Having a list of the modules belonging to each track in the [year ](https://mdef.fablabbcn.org/2023-24/year-1/) page or even in the home page (or somewhere else)
- [x] Adding the Edit button (Pencil Icon) like we had in the past at Smart Citizen to open the page in Github for quick editing. (Only if the current version supports it. No need to do a custom workaround if it doesn't anymore)
- [x] Adding a top level Glossary page to be populated with MDEF key words with definitions

**Comment by oscgonfer** [comment]
As far as the Edit button, we should check https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=#code-actions

The edit is available if you have a repo_url. We hid it only to avoid the icon on the top right to show (the github repo one).

Maybe @peters-rebecca finds a good solution for this compromise.

**However** for faculty pages, this won't be possible a priori, unless there is a config "per_page" because faculty are generated by macros.

**Comment by pral2a** [comment]
IMHO, I don't see it as a problem to have the upper badge. It could be smaller, but promoting the webpage as an open, editable and replicable resource is crucial. At the end of the day, it is about an open knowledge session.

**Comment by pral2a** [comment]
@peters-rebecca I created a separate issue for the Glossary Section https://github.com/fablabbcn/mdef-docs/issues/6

**Comment by oscgonfer** [comment]
> IMHO, I don't see it as a problem to have the upper badge.

Me neither. But it was done like that for aesthetic reasons I guess

**Comment by peters-rebecca** [comment]
@pral2a Edit button and source code button enabled.

**Comment by peters-rebecca** [comment]
I think this is all closed now. Reopen if needed.
